Movie details card
kate-eversunny/movies pull request #2
Opened 2021-07-15 12:21 UTC by kate-eversunny

2021-07-16 08:20 UTC, NikolayUkhvarov requested changes

2021-07-16 08:20 UTC, NikolayUkhvarov commented on app/src/main/res/values/dimen.xml
> +	<dimen name="poster_height">290sp</dimen>
тут должны быть dp, а не sp
sp - для размера текста

2021-07-19 07:48 UTC, kate-eversunny commented on app/src/main/res/values/dimen.xml
> +	<dimen name="poster_height">290sp</dimen>
Вторым коммитом внесла требуемые изменения: [https://github.com/kate-eversunny/movies/pull/2/commits/6498a56a49bf4c06040963c5b4550e805d6e106b](url)

2021-07-20 07:09 UTC, kate-eversunny commented on app/src/main/res/values/dimen.xml
> +	<dimen name="poster_height">290sp</dimen>
Исправлены наименования айдишников: https://github.com/kate-eversunny/movies/pull/2/commits/795aa096c0e943a3527bd764928891369f160fb9

2021-07-20 19:16 UTC, NikolayUkhvarov approved these changes

2021-07-21 06:45 UTC, merged