Movie list
kate-eversunny/movies pull request #3
Opened 2021-07-23 13:22 UTC by kate-eversunny

Создание экрана со списком фильмов (коммит 003f2c9)
Для проверки использования diffUtil список с фильмами можно однократно обновить, потянув его вниз (используется SwipeRefreshLayout со SwipeRefreshListener)

2021-07-23 14:03 UTC, NikolayUkhvarov requested changes

2021-07-23 14:03 UTC, NikolayUkhvarov commented on app/src/main/res/layout-land/item_movie.xml
> +<?xml version="1.0" encoding="utf-8"?>
снова отступы по 3 5 9 с:
повторяющиеся отступы в dimens, туда же размеры текста
(в других лэйаутах тоже)

2021-07-23 14:03 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MoviesViewHolder.kt
> +		val position: Int = this.layoutPosition
попробуй убрать логику из вьюхолдера

2021-07-25 15:35 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MoviesViewHolder.kt
> +		val position: Int = this.layoutPosition
Коммитом  f6a8a36 перенесла логику в адаптер. Также обновила отображение тостов, чтобы они не запускались, пока висит предыдущий тост.

2021-07-25 15:37 UTC, kate-eversunny commented on app/src/main/res/layout-land/item_movie.xml
> +<?xml version="1.0" encoding="utf-8"?>
Коммитом f6a8a36 обновила отступы, некоторые округлила, большинство сохранила в dimens.
Также обновила звездочки в рейтинг баре, чтобы они корректно отображались.

2021-07-26 17:54 UTC, NikolayUkhvarov approved these changes

2021-07-27 06:39 UTC, merged