Fragment
kate-eversunny/movies pull request #5
Opened 2021-07-29 20:19 UTC by kate-eversunny

movieList и movieDetails перенесены в фрагменты и привязаны к кнопке "Home" нижней панели навигации.
profile (сверстан "скелет" профиля для демонстрации навигации) привязан к кнопке "Профиль" нижней панели навигации.
По клику на элемент списка фильмов открывается карточка фильма. Отображение актеров реализовано с помощью RecyclerView

2021-07-31 12:45 UTC, NikolayUkhvarov requested changes

2021-07-31 12:45 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MovieDetailsFragment.kt
> +	companion object {
компаньон обычно в низу класса

2021-07-31 12:45 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MovieDetailsFragment.kt
> +			args.putParcelable("movie", movie)
не хардкодь строки

2021-07-31 12:45 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MovieDetailsFragment.kt
> +		val itemDecoration = MovieItemDecoration(10, 0,10, 50)
какие-то магические числа

2021-07-31 12:45 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +			moviesModel.setMovies(savedInstanceState.getParcelableArrayList<MovieDto>("savedMoviesList") as ArrayList<MovieDto>)
еще хардкод

2021-07-31 12:45 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +		val itemDecoration = MovieItemDecoration(20, 0,20, 50)
и еще числа

2021-07-31 12:45 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +	companion object {
тут тоже

2021-07-31 12:45 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/ProfileFragment.kt
> +	companion object {
и тут

2021-07-31 20:19 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MovieDetailsFragment.kt
> +	companion object {
Перенесла в низ класса 
85cb2ae

2021-07-31 20:19 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MovieDetailsFragment.kt
> +			args.putParcelable("movie", movie)
Перенесла строки в strings
85cb2ae

2021-07-31 20:19 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MovieDetailsFragment.kt
> +		val itemDecoration = MovieItemDecoration(10, 0,10, 50)
Перенесла в dimens
85cb2ae

2021-07-31 20:20 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +			moviesModel.setMovies(savedInstanceState.getParcelableArrayList<MovieDto>("savedMoviesList") as ArrayList<MovieDto>)
Перенесла в strings
85cb2ae

2021-07-31 20:20 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +		val itemDecoration = MovieItemDecoration(20, 0,20, 50)
Перенесла в dimens
85cb2ae

2021-07-31 20:21 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +	companion object {
Перенесла в низ класса
85cb2ae

2021-07-31 20:21 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/ProfileFragment.kt
> +	companion object {
Перенесла в низ класса
85cb2ae

2021-08-03 07:37 UTC, NikolayUkhvarov approved these changes

2021-08-04 09:11 UTC, merged