Update MoviesListFragment for loading movies through coroutines
kate-eversunny/movies pull request #6
Opened 2021-08-04 16:50 UTC by kate-eversunny

Список фильмов загружается и обновляется с помощью корутин.

2021-08-05 11:50 UTC, NikolayUkhvarov requested changes

2021-08-05 11:50 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +		Thread.sleep(UPDATE_DELAY)
вынеси в getMovies()
чтобы задержка была не на стороне обработки

2021-08-05 11:50 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +			Thread.sleep(UPDATE_DELAY)
и тут

2021-08-06 09:19 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +		Thread.sleep(UPDATE_DELAY)
Обновила в коммите 
bfc1d7b

2021-08-06 09:19 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/MoviesListFragment.kt
> +			Thread.sleep(UPDATE_DELAY)
Обновила в коммите 
bfc1d7b

2021-08-08 14:22 UTC, NikolayUkhvarov approved these changes

2021-08-08 18:21 UTC, merged