Change architecture to MVVM and add navigation
kate-eversunny/movies pull request #8
Opened 2021-08-12 07:25 UTC by kate-eversunny

2021-08-12 17:37 UTC, NikolayUkhvarov requested changes

2021-08-12 17:37 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/fragments/MovieDetailsFragment.kt
> +			args.putParcelable(TAG_MOVIE, movie)
нужно передавать сюда только id фильма
создать вьюмодель для этого экрана и через нее получить фильм по id

2021-08-12 17:37 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/fragments/MoviesListFragment.kt
> +		runBlocking {
без runBlocking
вью должна только отобразить список из вьюмодели
адаптер можно инициализировать пустым
и когда уже вьюмодель получить данные - отобразить в updateData()

2021-08-12 17:37 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/fragments/MoviesListFragment.kt
>  			scope.launch(handler) {
без корутин во вью

2021-08-12 17:37 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/viewModel/MovieViewModel.kt
> +		return data.value!!
нужно стараться не использовать !!

2021-08-12 17:37 UTC, NikolayUkhvarov commented on app/src/main/java/com/example/myapplication/viewModel/MovieViewModel.kt
> +		return data.value!!
и тут

2021-08-13 19:57 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/fragments/MovieDetailsFragment.kt
> +			args.putParcelable(TAG_MOVIE, movie)
Исправлено коммитом 
6f2cc7c

2021-08-13 19:57 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/fragments/MoviesListFragment.kt
> +		runBlocking {
Исправлено коммитом 
6f2cc7c

2021-08-13 19:57 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/fragments/MoviesListFragment.kt
>  			scope.launch(handler) {
Исправлено коммитом 
6f2cc7c

2021-08-13 19:57 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/viewModel/MovieViewModel.kt
> +		return data.value!!
Исправлено коммитом 
6f2cc7c

2021-08-13 19:57 UTC, kate-eversunny commented on app/src/main/java/com/example/myapplication/viewModel/MovieViewModel.kt
> +		return data.value!!
Исправлено коммитом 
6f2cc7c

2021-08-18 12:09 UTC, NikolayUkhvarov approved these changes

2021-08-18 12:19 UTC, merged